name: 'Packages Split'

on:
  push:
    branches:
      - master
    tags:
      - '*'

env:
  GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}

jobs:
  packages_split:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        package:
          -
            local_path: 'package1'
            split_repository: 'package1'
          - local_path: 'package2'
            split_repository: 'package2'

    steps:
      -   uses: actions/checkout@v2

      # no tag
      -
        if: "!startsWith(github.ref, 'refs/tags/')"
        uses: "symplify/monorepo-split-github-action@2.1"
        with:
          package_directory: 'packages/${{ matrix.package.local_path }}'
          repository_organization: 'fabricity'
          repository_name: '${{ matrix.package.split_repository }}'
          branch: "master"
          user_name: "fabricity"
          user_email: "info@fabricity.com"

      # with tag
      -
        if: "startsWith(github.ref, 'refs/tags/')"
        uses: "symplify/monorepo-split-github-action@2.1"
        with:
          tag: ${GITHUB_REF#refs/tags/}
          package_directory: 'packages/${{ matrix.package.local_path }}'
          repository_organization: 'fabricity'
          repository_name: '${{ matrix.package.split_repository }}'
          branch: "master"
          user_name: "fabricity"
          user_email: "info@fabricity.com"